spring:
  datasource:
    url: jdbc:mysql://${da.datasource.ip}:3306/user-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${da.datasource.username}
    password: ${da.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver